# Generated by Django 4.2.3 on 2023-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('wind', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=5, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
